CREATE TABLE kategori (
    id_kategori SERIAL PRIMARY KEY,
    kode_kategori VARCHAR(10) NOT NULL UNIQUE,
    nama_kategori VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE obat (
  id_obat SERIAL PRIMARY KEY,
  kode_obat VARCHAR(50) NOT NULL,
  nama_obat VARCHAR(100) NOT NULL,
  stok_obat INTEGER DEFAULT 0,
  harga_obat NUMERIC(12, 2),
  kode_kategori VARCHAR(50),
  kode_supplier VARCHAR(50)
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);